/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package designpatterns.Presenatationlayer;


import designpatterns.Logiclayer.OrderManager;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lorenzo
 */
public class MainGUI extends javax.swing.JFrame {

    DefaultListModel orderListModel = new DefaultListModel();
    OrderManager ordermanager = new OrderManager();
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        
    }
    
    public void update(){
        String add = ordermanager.getOrder();
        if(add != ""){               
            orderListModel.addElement(add);
            orderList.setModel(orderListModel);  
            ordermanager.setOrder("");
        }
    }

    public void setVisibility(boolean visibility){
        this.setVisible(visibility);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PCorderbutton = new javax.swing.JButton();
        laptoporderbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("New Order:");

        PCorderbutton.setText("PC");
        PCorderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCorderbuttonActionPerformed(evt);
            }
        });

        laptoporderbutton.setText("Laptop");
        laptoporderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptoporderbuttonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(orderList);

        jLabel2.setText("Current Orders:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(PCorderbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(laptoporderbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jLabel1)))
                        .addGap(0, 242, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCorderbutton)
                    .addComponent(laptoporderbutton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PCorderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCorderbuttonActionPerformed

        OrderFormPCGUI pcorder = new OrderFormPCGUI(this);
        pcorder.setVisible(true);
        setVisibility(false);
    }//GEN-LAST:event_PCorderbuttonActionPerformed

    private void laptoporderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptoporderbuttonActionPerformed
        OrderFormLaptopGUI laptoporder = new OrderFormLaptopGUI(this);
        laptoporder.setVisible(true);
        setVisibility(false);
    }//GEN-LAST:event_laptoporderbuttonActionPerformed
   
    
    public void sendOrderList(){
    
        orderListModel.clear();
        System.out.println("Orders zijn verzonden!");
        
    }
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PCorderbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton laptoporderbutton;
    private javax.swing.JList orderList;
    // End of variables declaration//GEN-END:variables
}
