/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package designpatterns.Presenatationlayer;


import designpatterns.Logiclayer.Concretes.BluetoothDecorator;
import designpatterns.Logiclayer.Concretes.ComputerBuilder;
import designpatterns.Logiclayer.Concretes.DriveDecorator;
import designpatterns.Logiclayer.Concretes.WebcamDecorator;
import designpatterns.Logiclayer.Concretes.sendLaptopOrderCommand;
import designpatterns.Logiclayer.Interfaces.IComputer;
import designpatterns.Logiclayer.OrderManager;
import java.util.ArrayList;

/**
 *
 * @author Lorenzo
 */
public class OrderFormLaptopGUI extends javax.swing.JFrame {

    
    OrderManager ordermanager = new OrderManager();
    ComputerBuilder compBuilder;

    Boolean Extradrive=false;
    String driveString="";
    Boolean Extrawebcam=false;  
    String webcamString="";
    Boolean Extrabluetooth=false;
    String bluetoothString="";

MainGUI MainGUI;
    /**
     * Creates new form OrderFormLaptopGUI
     */
    public OrderFormLaptopGUI(MainGUI CurrentGUI) {
        initComponents();
        this.setTitle("Laptop order GUI");
        osComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Windows XP", "Windows 7", "Windows 8", "Mac OSX", "Ubuntu" }));
        processorComboboxlaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AMD", "Intel" }));
        ramComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2GB", "4GB", "6GB", "8GB", "12GB", "16GB" }));
        memoryComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "128GB", "256GB", "512GB","768GB" ,"1TB", "2TB" }));
        screensizeComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 inch", "11 inch", "13 inch","15 inch" ,"17 inch" }));
        screenresComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1024 x 768", "1280 x 1024", "1366 x 768","1600 x 900" ,"1680 x 1050", "1920 x 1080", "2560 x 1440" }));
        videoComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AMD", "nVidia", "Intel" }));
        audioComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Realtek Audio", "Dolby Sound System" }));
        brandComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HP", "Dell", "MSI","Lenovo" ,"Samsung", "Apple", "Alienware", "Acer", "ASUS", "Sony", "Toshiba" }));
        colorComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "White", "Grey", "Black","Red" ,"Green", "Yellow", "Blue" }));
        driveComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CD-Drive", "CD & DVD-Drive", "Bluray + CD/DVD" }));
        driveComboboxLaptop.setEnabled(false);
        webcamComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SD", "720P", "1080P" }));
        webcamComboboxLaptop.setEnabled(false);
        USBComboboxLaptop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8"}));
        
         MainGUI=CurrentGUI; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        osComboboxLaptop = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        processorComboboxlaptop = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        ramComboboxLaptop = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        memoryComboboxLaptop = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        screensizeComboboxLaptop = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        screenresComboboxLaptop = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        videoComboboxLaptop = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        audioComboboxLaptop = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        brandComboboxLaptop = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        colorComboboxLaptop = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        driveCheckBox = new javax.swing.JCheckBox();
        webcamCheckboxLaptop = new javax.swing.JCheckBox();
        bluetoothCheckBox = new javax.swing.JCheckBox();
        driveComboboxLaptop = new javax.swing.JComboBox();
        webcamComboboxLaptop = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        USBComboboxLaptop = new javax.swing.JComboBox();
        hdmiCheckBoxLaptop = new javax.swing.JCheckBox();
        sdCheckBoxLaptop = new javax.swing.JCheckBox();
        vgaCheckBoxLaptop = new javax.swing.JCheckBox();
        dviCheckBoxLaptop = new javax.swing.JCheckBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Terug");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("OS:");

        osComboboxLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osComboboxLaptopActionPerformed(evt);
            }
        });

        jLabel2.setText("Processor:");

        jLabel3.setText("RAM:");

        jLabel4.setText("Memory:");

        jLabel5.setText("Screensize:");

        jLabel6.setText("Screenres:");

        jLabel7.setText("Video:");

        jLabel8.setText("Audio:");

        jLabel9.setText("Brand:");

        jLabel10.setText("Color:");

        jButton2.setText("Invoeren");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Extras:");

        driveCheckBox.setText("Drive");
        driveCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driveCheckBoxActionPerformed(evt);
            }
        });

        webcamCheckboxLaptop.setText("Webcam");
        webcamCheckboxLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webcamCheckboxLaptopActionPerformed(evt);
            }
        });

        bluetoothCheckBox.setText("Bluetooth");

        jLabel12.setText("Ports:");

        jLabel13.setText("USB:");

        hdmiCheckBoxLaptop.setText("HDMI");
        hdmiCheckBoxLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdmiCheckBoxLaptopActionPerformed(evt);
            }
        });

        sdCheckBoxLaptop.setText("SD");
        sdCheckBoxLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdCheckBoxLaptopActionPerformed(evt);
            }
        });

        vgaCheckBoxLaptop.setText("VGA");

        dviCheckBoxLaptop.setText("DVI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(osComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(processorComboboxlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ramComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(audioComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(videoComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(screenresComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(screensizeComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(memoryComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brandComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(driveCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(driveComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webcamCheckboxLaptop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(webcamComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(USBComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bluetoothCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hdmiCheckBoxLaptop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sdCheckBoxLaptop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vgaCheckBoxLaptop)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dviCheckBoxLaptop))
                                    .addComponent(jLabel12))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(osComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(processorComboboxlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ramComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memoryComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screensizeComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenresComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(videoComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(audioComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driveCheckBox)
                    .addComponent(driveComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webcamCheckboxLaptop)
                    .addComponent(webcamComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bluetoothCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(USBComboboxLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hdmiCheckBoxLaptop)
                    .addComponent(sdCheckBoxLaptop)
                    .addComponent(vgaCheckBoxLaptop)
                    .addComponent(dviCheckBoxLaptop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainGUI order = new MainGUI();
        order.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void osComboboxLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osComboboxLaptopActionPerformed
        
    }//GEN-LAST:event_osComboboxLaptopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String os = "OS: ";
        os += (String)osComboboxLaptop.getSelectedItem();
        String processor = "Processor: ";
        processor += (String)processorComboboxlaptop.getSelectedItem();
        String memory = "Memory: ";
        memory += (String)memoryComboboxLaptop.getSelectedItem();
        String ram = "Ram: ";
        ram += (String)ramComboboxLaptop.getSelectedItem();
        String audio = "Audio: ";
        audio += (String)audioComboboxLaptop.getSelectedItem();
        String brand = "Brand: ";
        brand += (String)brandComboboxLaptop.getSelectedItem();
        String color = "Color: ";
        color += (String)colorComboboxLaptop.getSelectedItem();
        String drive = "";
        if(driveCheckBox.isSelected()){
            drive = "Drive: ";
            drive += (String)driveComboboxLaptop.getSelectedItem();
            Extradrive=true;
            driveString=(String)driveComboboxLaptop.getSelectedItem();
        }
        String webcam = "Webcam: None";
        if(webcamCheckboxLaptop.isSelected()){
            webcam = "Webcam: ";
            webcam += (String)webcamComboboxLaptop.getSelectedItem();
            Extrawebcam=true;
            webcamString=(String)webcamComboboxLaptop.getSelectedItem();
        }
        String bluetooth = "Bluetooth Adapter: No";
        if(bluetoothCheckBox.isSelected()){
            bluetooth = "Bluetooth Adapter: Yes";
            Extrabluetooth=true;
            bluetoothString="Yes";
        }
        
        String hdmi = "HDMI port: No";
        if(hdmiCheckBoxLaptop.isSelected()){
            hdmi = "HDMI port: Yes";
        }
        
        String vga = "VGA port: no";
        if(vgaCheckBoxLaptop.isSelected()){
            vga = "VGA port: yes";
        }
        
        String dvi = "DVI port: no";
        if(dviCheckBoxLaptop.isSelected()){
            dvi = "DVI port: yes";
        }
        
        String usb = "USB poorten: ";
        usb += (String)USBComboboxLaptop.getSelectedItem();
        
               
        String orderRegel = os +" - " + processor + " - " + ram + " - "+ memory + " - " + audio + " - " + brand + " - " + color + " - " + drive + " - " + webcam + " - " + bluetooth + " - " + usb + " - " + vga + " - " + hdmi + " - " + dvi;
        ordermanager.setOrder(orderRegel);
        
        ArrayList orderArray= new ArrayList<String>();
        
        orderArray.add(os);
        orderArray.add(ram);
        orderArray.add(processor);
                
        sendLaptopOrderCommand command=new sendLaptopOrderCommand(orderArray);
        
        IComputer comp = command.execute();
        compBuilder=command.getCompBuilder();
        
        checkExtras(comp);
       
        comp.displaySpecs();
        comp.displayExtras();
        
        MainGUI.setVisibility(true);
        MainGUI.update();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void driveCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driveCheckBoxActionPerformed
      if(driveCheckBox.isSelected()){  
        driveComboboxLaptop.setEnabled(true);
      }else{
        driveComboboxLaptop.setEnabled(false);
      }
    }//GEN-LAST:event_driveCheckBoxActionPerformed

    private void webcamCheckboxLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webcamCheckboxLaptopActionPerformed
      if(webcamCheckboxLaptop.isSelected()){  
        webcamComboboxLaptop.setEnabled(true);
      }else{
        webcamComboboxLaptop.setEnabled(false);
      }
    }//GEN-LAST:event_webcamCheckboxLaptopActionPerformed

    private void hdmiCheckBoxLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdmiCheckBoxLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hdmiCheckBoxLaptopActionPerformed

    private void sdCheckBoxLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdCheckBoxLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdCheckBoxLaptopActionPerformed

    public IComputer checkExtras(IComputer comp){
        
        IComputer decoComp = comp;
        
        if(Extradrive==true){
            DriveDecorator deco=new DriveDecorator();
            compBuilder.decorateComputer(deco,comp,driveString);
             
        }
        if(Extrawebcam==true){
            WebcamDecorator deco=new WebcamDecorator();
            compBuilder.decorateComputer(deco,comp,webcamString);
        }
        if(Extrabluetooth==true){
            BluetoothDecorator deco=new BluetoothDecorator();
            compBuilder.decorateComputer(deco,comp,bluetoothString);
        }
        
        return decoComp;
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox USBComboboxLaptop;
    private javax.swing.JComboBox audioComboboxLaptop;
    private javax.swing.JCheckBox bluetoothCheckBox;
    private javax.swing.JComboBox brandComboboxLaptop;
    private javax.swing.JComboBox colorComboboxLaptop;
    private javax.swing.JCheckBox driveCheckBox;
    private javax.swing.JComboBox driveComboboxLaptop;
    private javax.swing.JCheckBox dviCheckBoxLaptop;
    private javax.swing.JCheckBox hdmiCheckBoxLaptop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox memoryComboboxLaptop;
    private javax.swing.JComboBox osComboboxLaptop;
    private javax.swing.JComboBox processorComboboxlaptop;
    private javax.swing.JComboBox ramComboboxLaptop;
    private javax.swing.JComboBox screenresComboboxLaptop;
    private javax.swing.JComboBox screensizeComboboxLaptop;
    private javax.swing.JCheckBox sdCheckBoxLaptop;
    private javax.swing.JCheckBox vgaCheckBoxLaptop;
    private javax.swing.JComboBox videoComboboxLaptop;
    private javax.swing.JCheckBox webcamCheckboxLaptop;
    private javax.swing.JComboBox webcamComboboxLaptop;
    // End of variables declaration//GEN-END:variables
}
